marca=" olá mundo "
Palavra=(input("escreva uma frase"))
print(len(Palavra))
print(marca)
marca= (marca.upper())
print (marca)
marca= (marca.lower())
print (marca)
marca=(marca.capitalize())
print (marca)
print(marca.strip())